katana_gripper:
  type: position_controllers/JointTrajectoryController
  joints:
    - katana_l_finger_joint
    - katana_r_finger_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    gripper_finger_joint: {trajectory: 0.2, goal: 0.2}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10
  gripper_pid:
    p: 0.4
    d: 0.1
    i: 0.0
    i_clamp: 0.0


katana:
  gripper_pid:
    p: 0.4
    d: 0.1
    i: 0.0
    i_clamp: 0.0

